# Generated by Django 3.2.7 on 2021-11-26 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20211126_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='product_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='harddrive',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='ram',
            field=models.CharField(default='', max_length=100),
        ),
    ]
